const mangas = [
    {
        "title": "19 Days",
        "alternativeTitles": ["19 Tian"],
        "link": "../19 Days/Obra.html",
        "image": "../../../../img/mangas/19-Days.jpg",
        "type": "Manhua",
        "year": "2014",
    },
    {
        "title": "20th Century Boys",
        "alternativeTitles": ["20 Seiki Shounen"],
        "link": "../20th Century Boys/Obra.html",
        "image": "../../../../img/mangas/20th-Century-Boys.jpg",
        "type": "Mangá",
        "year": "1999 - 2006",
    },
    {
        "title": "A Business Proposal",
        "alternativeTitles": ["The Office Blind Date", "Sanae Matseon"],
        "link": "../A Business Proposal/Obra.html",
        "image": "../../../../img/mangas/A-Business-Proposal.jpg",
        "type": "Manhwa",
        "year": "2018 - 2022",
    },
    {
        "title": "After School Lessons for Unripe Apples",
        "alternativeTitles": ["90's Cram School for Unripe Apples"],
        "link": "../After School Lessons for Unripe Apples/Obra.html",
        "image": "../../../../img/mangas/After-School-Lessons for-Unripe-Apples.jpg",
        "type": "Manhwa",
        "year": "2020",
    },
    {
        "title": "Ajin: Demi-Human",
        "alternativeTitles": ["Ajin"],
        "link": "../obras/Ajin Demi-Human/Obra.html",
        "image": "../../../../img/mangas/Ajin-Demi-Human.jpg",
        "type": "Mangá",
        "year": "2012 - 2021",
    },
    {
        "title": "Akame ga Kill!",
        "alternativeTitles": [""],
        "link": "../obras/Akame ga Kill!/Obra.html",
        "image": "../../../../img/mangas/Akame-ga-Kill!.jpg",
        "type": "Mangá",
        "year": "2010 - 2016",
    },
    {
        "title": "Banana Fish",
        "alternativeTitles": [""],
        "link": "../Banana Fish/Obra.html",
        "image": "../../../../img/mangas/Banana-Fish.jpg",
        "type": "Mangá",
        "year": "1985 - 1994",
    },
    {
        "title": "Berserk",
        "alternativeTitles": [""],
        "link": "../Berserk/Obra.html",
        "image": "../../../../img/mangas/Berserk.jpg",
        "type": "Mangá",
        "year": "1989",
    },
    {
        "title": "Beware of the Villainess!",
        "alternativeTitles": ["Geu Angnyeoreul Josimhaseyo!"],
        "link": "../Beware of the Villainess!/Obra.html",
        "image": "../../../../img/mangas/Beware-of-the-Villainess!.jpg",
        "type": "Manhwa",
        "year": "2020 - 2022",
    },
    {
        "title": "Black Clover",
        "alternativeTitles": [""],
        "link": "../Black Clover/Obra.html",
        "image": "../../../../img/mangas/Black-Clover.jpg",
        "type": "Mangá",
        "year": "2015",
    },
    {
        "title": "Bleach",
        "alternativeTitles": [""],
        "link": "../Bleach/Obra.html",
        "image": "../../../../img/mangas/Bleach.jpg",
        "type": "Mangá",
        "year": "2002 - 2016",
    },
    {
        "title": "Boku no Hero Academia",
        "alternativeTitles": ["My Hero Academia"],
        "link": "../Boku no Hero Academia/Obra.html",
        "image": "../../../../img/mangas/Boku-no-Hero-Academia.jpg",
        "type": "Mangá",
        "year": "2014 - 2024",
    },
    {
        "title": "Chainsaw Man",
        "alternativeTitles": [""],
        "link": "../Chainsaw Man/Obra.html",
        "image": "../../../../img/mangas/Chainsaw-Man.jpg",
        "type": "Mangá",
        "year": "2018",
    },
    {
        "title": "Choujin X",
        "alternativeTitles": [""],
        "link": "../Choujin X/Obra.html",
        "image": "../../../../img/mangas/Choujin-X.jpg",
        "type": "Mangá",
        "year": "2021",
    },
    {
        "title": "Claymore",
        "alternativeTitles": [""],
        "link": "../obras/Claymore/Obra.html",
        "image": "../../../../img/mangas/Claymore.jpg",
        "type": "Mangá",
        "year": "2001 - 2014",
    },
    {
        "title": "Dandadan",
        "alternativeTitles": [""],
        "link": "../obras/Dandadan/Obra.html",
        "image": "../../../../img/mangas/Dandadan.jpg",
        "type": "Mangá",
        "year": "2021",
    },
    {
        "title": "Daytime Star",
        "alternativeTitles": [""],
        "link": "../Daytime Star/Obra.html",
        "image": "../../../../img/mangas/Daytime-Star.jpg",
        "type": "Manhwa",
        "year": "2021 - 2023",
    },
    {
        "title": "Deadman Wonderland",
        "alternativeTitles": [""],
        "link": "../obras/Deadman Wonderland/Obra.html",
        "image": "../../../../img/mangas/Deadman-Wonderland.jpg",
        "type": "Mangá",
        "year": "2007 - 2013",
    },
    {
        "title": "Death Note",
        "alternativeTitles": [""],
        "link": "../Death Note/Obra.html",
        "image": "../../../../img/mangas/Death-Note.jpg",
        "type": "Mangá",
        "year": "2003 - 2006",
    },
    {
        "title": "Devilman",
        "alternativeTitles": [""],
        "link": "../obras/Devilman/Obra.html",
        "image": "../../../../img/mangas/Devilman.jpg",
        "type": "Mangá",
        "year": "1972 - 1973",
    },
    {
        "title": "Director Kim",
        "alternativeTitles": ["Kim Bujang", "Manager Kim"],
        "link": "../Director Kim/Obra.html",
        "image": "../../../../img/mangas/Director-Kim.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "Dorohedoro",
        "alternativeTitles": [""],
        "link": "../Dorohedoro/Obra.html",
        "image": "../../../../img/mangas/Dorohedoro.jpg",
        "type": "Mangá",
        "year": "2000 - 2018",
    },
    {
        "title": "Dr. Stone",
        "alternativeTitles": [""],
        "link": "../Dr. Stone/Obra.html",
        "image": "../../../../img/mangas/Dr.-Stone.jpg",
        "type": "Mangá",
        "year": "2017 - 2022",
    },
    {
        "title": "Dreaming Freedom",
        "alternativeTitles": ["Free in Dreams", "Kkumeseo Jayuro"],
        "link": "../Dreaming Freedom/Obra.html",
        "image": "../../../../img/mangas/Dreaming-Freedom.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "Eleceed",
        "alternativeTitles": [""],
        "link": "../Eleceed/Obra.html",
        "image": "../../../../img/mangas/Eleceed.jpg",
        "type": "Manhwa",
        "year": "2018",
    },
    {
        "title": "Elfen Lied",
        "alternativeTitles": [""],
        "link": "../Elfen Lied/Obra.html",
        "image": "../../../../img/mangas/Elfen-Lied.jpg",
        "type": "Mangá",
        "year": "2002 - 2005",
    },
    {
        "title": "Fairy Tail",
        "alternativeTitles": [""],
        "link": "../obras/Fairy Tail/Obra.html",
        "image": "../../../../img/mangas/Fairy-Tail.jpg",
        "type": "Mangá",
        "year": " 2006 - 2017",
    },
    {
        "title": "Fire Punch",
        "alternativeTitles": [""],
        "link": "../Fire Punch/Obra.html",
        "image": "../../../../img/mangas/Fire-Punch.jpg",
        "type": "Mangá",
        "year": "2016 - 2018",
    },
    {
        "title": "Fullmetal Alchemist",
        "alternativeTitles": [""],
        "link": "../Fullmetal Alchemist/Obra.html",
        "image": "../../../../img/mangas/Fullmetal-Alchemist.jpg",
        "type": "Mangá",
        "year": "2001 - 2010",
    },
    {
        "title": "Gangsta.",
        "alternativeTitles": [""],
        "link": "../Gangsta/Obra.html",
        "image": "../../../../img/mangas/Gangsta.jpg",
        "type": "Mangá",
        "year": "2011",
    },
    {
        "title": "Gantz",
        "alternativeTitles": [""],
        "link": "../Gantz/Obra.html",
        "image": "../../../../img/mangas/Gantz.jpg",
        "type": "Mangá",
        "year": "2000 - 2013",
    },
    {
        "title": "Gintama",
        "alternativeTitles": [""],
        "link": "../Gintama/Obra.html",
        "image": "../../../../img/mangas/Gintama.jpg",
        "type": "Mangá",
        "year": "2003 - 2019",
    },
    {
        "title": "Gokushufudou",
        "alternativeTitles": ["The Way of the Househusband"],
        "link": "../Gokushufudou/Obra.html",
        "image": "../../../../img/mangas/Gokushufudou.jpg",
        "type": "Mangá",
        "year": "2018",
    },
    {
        "title": "Guard Pass",
        "alternativeTitles": [""],
        "link": "../Guard Pass/Obra.html",
        "image": "../../../../img/mangas/Guard-Pass.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "Haikyuu!!",
        "alternativeTitles": [""],
        "link": "../Haikyuu!!/Obra.html",
        "image": "../../../../img/mangas/Haikyuu!!.jpg",
        "type": "Mangá",
        "year": "2012 - 2020",
    },
    {
        "title": "Heaven Official's Blessing",
        "alternativeTitles": ["Tian Guan Ci Fu"],
        "link": "../Heaven Official_s Blessing (novel)/Obra.html",
        "image": "../../../../img/mangas/Heaven-Official_s-Blessing-_novel_.jpg",
        "type": "Light Novel",
        "year": "2017 - 2018",
    },
    {
        "title": "Heaven Official's Blessing",
        "alternativeTitles": ["Tian Guan Ci Fu"],
        "link": "../Heaven Official_s Blessing/Obra.html",
        "image": "../../../../img/mangas/Heaven-Official_s-Blessing.jpg",
        "type": "Manhua",
        "year": "2019",
    },
    {
        "title": "Hellsing",
        "alternativeTitles": [""],
        "link": "../Hellsing/Obra.html",
        "image": "../../../../img/mangas/Hellsing.jpg",
        "type": "Mangá",
        "year": "1997 - 2008",
    },
    {
        "title": "Hero Killer",
        "alternativeTitles": [""],
        "link": "../Hero Killer/Obra.html",
        "image": "../../../../img/mangas/Hero-Killer.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "How to Fight",
        "alternativeTitles": [""],
        "link": "../How to Fight/Obra.html",
        "image": "../../../../img/mangas/How-to-Fight.jpg",
        "type": "Manhwa",
        "year": "2016 - 2024",
    },
    {
        "title": "Hunter x Hunter",
        "alternativeTitles": [""],
        "link": "../Hunter x Hunter/Obra.html",
        "image": "../../../../img/mangas/Hunter-x-Hunter.jpg",
        "type": "Mangá",
        "year": "1998",
    },
    {
        "title": "Hwiyeong Geomjeon",
        "alternativeTitles": ["Biography of Hwiyeong Sword"],
        "link": "../Hwiyeong Geomjeon/Obra.html",
        "image": "../../../../img/mangas/Hwiyeong-Geomjeon.jpg",
        "type": "Manhwa",
        "year": "2023",
    },
    {
        "title": "I Became the Male Lead’s Adopted Daughter",
        "alternativeTitles": ["Namjuui Ibyangttari Doeeotseumnida", "The Male Lead's Little Lion Daughter"],
        "link": "../I Became the Male Lead’s Adopted Daughter/Obra.html",
        "image": "../../../../img/mangas/I-Became-the-Male-Lead’s-Adopted-Daughter.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "Ijiranaide, Nagatoro-san",
        "alternativeTitles": ["Don't Toy With Me", "Miss Nagatoro"],
        "link": "../Ijiranaide, Nagatoro-san/Obra.html",
        "image": "../../../../img/mangas/Ijiranaide,-Nagatoro-san.jpg",
        "type": "Mangá",
        "year": "2017 - 2024",
    },
    {
        "title": "InuYasha",
        "alternativeTitles": [""],
        "link": "../InuYasha/Obra.html",
        "image": "../../../../img/mangas/InuYasha.jpg",
        "type": "Mangá",
        "year": "1996 - 2008",
    },
    {
        "title": "Jagaaaaaan",
        "alternativeTitles": [""],
        "link": "../Jagaaaaaan/Obra.html",
        "image": "../../../../img/mangas/Jagaaaaaan.jpg",
        "type": "Mangá",
        "year": "2017 - 2021",
    },
    {
        "title": "Jibaku Shounen Hanako-kun",
        "alternativeTitles": ["Toilet-Bound Hanako-kun"],
        "link": "../Jibaku Shounen Hanako-kun/Obra.html",
        "image": "../../../../img/mangas/Jibaku-Shounen-Hanako-kun.jpg",
        "type": "Mangá",
        "year": "2014",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 1: Phantom Blood",
        "alternativeTitles": ["JoJo no Kimyou na Bouken Part 1: Phantom Blood"],
        "link": "../JoJo’s Bizarre Adventure Part 1/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-1.jpg",
        "type": "Mangá",
        "year": "1986 - 1987",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 2: Battle Tendency",
        "alternativeTitles": ["JoJo no Kimyou na Bouken Part 2: Sentou Chuuryuu"],
        "link": "../JoJo’s Bizarre Adventure Part 2/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-2.jpg",
        "type": "Mangá",
        "year": "1987 - 1989",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 3: Stardust Crusaders",
        "alternativeTitles": ["JoJo no Kimyou na Bouken Part 3: Stardust Crusaders"],
        "link": "../JoJo’s Bizarre Adventure Part 3/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-3.jpg",
        "type": "Mangá",
        "year": "1989 - 1992",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 4: Diamond is Unbreakable",
        "alternativeTitles": ["JoJo no Kimyou na Bouken: Diamond wa Kudakenai"],
        "link": "../JoJo’s Bizarre Adventure Part 4/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-4.jpg",
        "type": "Mangá",
        "year": "1992 - 1995",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 5: Golden Wind",
        "alternativeTitles": ["JoJo no Kimyou na Bouken Part 5: Ougon no Kaze", "JoJo's Bizarre Adventure Part 5: Vento Aureo"],
        "link": "../JoJo’s Bizarre Adventure Part 5/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-5.jpg",
        "type": "Mangá",
        "year": "1995 - 1999",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 6: Stone Ocean",
        "alternativeTitles": ["Jojo no Kimyou na Bouken: Stone Ocean"],
        "link": "../JoJo’s Bizarre Adventure Part 6/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-6.jpg",
        "type": "Mangá",
        "year": "1999 - 2003",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 7: Steel Ball Run",
        "alternativeTitles": ["Jojo no Kimyou na Bouken: Steel Ball Run"],
        "link": "../JoJo’s Bizarre Adventure Part 7/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-7.jpg",
        "type": "Mangá",
        "year": "2004 - 2011",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 8: Jojolion",
        "alternativeTitles": ["Jojo no Kimyou na Bouken: Jojorion"],
        "link": "../JoJo’s Bizarre Adventure Part 8/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-8.jpg",
        "type": "Mangá",
        "year": "2011 - 2021",
    },
    {
        "title": "JoJo's Bizarre Adventure Part 9: The JOJOLands",
        "alternativeTitles": ["Jojo no Kimyou na Bouken: The JOJOLands"],
        "link": "../JoJo’s Bizarre Adventure Part 9/Obra.html",
        "image": "../../../../img/mangas/JoJo’s-Bizarre-Adventure-Part-9.jpg",
        "type": "Mangá",
        "year": "2023",
    },
    {
        "title": "Jujutsu Kaisen",
        "alternativeTitles": ["Sorcery Fight"],
        "link": "../Jujutsu Kaisen/Obra.html",
        "image": "../../../../img/mangas/Jujutsu-Kaisen.jpg",
        "type": "Mangá",
        "year": "2018",
    },
    {
        "title": "Just Leave Me Be",
        "alternativeTitles": ["Nareul Beoryeojuseyo", "Please Throw Me Away"],
        "link": "../Just Leave Me Be/Obra.html",
        "image": "../../../../img/mangas/Just-Leave-Me-Be.jpg",
        "type": "Manhwa",
        "year": "2020 - 2023",
    },
    {
        "title": "Kaiju No. 8",
        "alternativeTitles": ["Kaijuu 8-gou", "Monster #8"],
        "link": "../Kaijuu 8-gou/Obra.html",
        "image": "../../../../img/mangas/Kaijuu-8-gou.jpg",
        "type": "Mangá",
        "year": "2020",
    },
    {
        "title": "Kill the Villainess",
        "alternativeTitles": ["Agnyeoreul Jugyeo Jwo"],
        "link": "../Kill the Villainess/Obra.html",
        "image": "../../../../img/mangas/Kill-the-Villainess.jpg",
        "type": "Manhwa",
        "year": "2021 - 2024",
    },
    {
        "title": "Killer Cop",
        "alternativeTitles": ["Return of the Bloodthirsty Police"],
        "link": "../Killer Cop/Obra.html",
        "image": "../../../../img/mangas/Killer-Cop.jpg",
        "type": "Manhwa",
        "year": "2023",
    },
    {
        "title": "Killer Peter",
        "alternativeTitles": [""],
        "link": "../Killer Peter/Obra.html",
        "image": "../../../../img/mangas/Killer-Peter.jpg",
        "type": "Manhwa",
        "year": "2023",
    },
    {
        "title": "Kimetsu no Yaiba",
        "alternativeTitles": ["Demon Slayer"],
        "link": "../Kimetsu no Yaiba/Obra.html",
        "image": "../../../../img/mangas/Kimetsu-no-Yaiba.jpg",
        "type": "Mangá",
        "year": "2016 - 2020",
    },
    {
        "title": "Komi-san wa, Comyushou desu",
        "alternativeTitles": ["Komi Can't Communicate"],
        "link": "../Komi-san wa, Comyushou desu/Obra.html",
        "image": "../../../../img/mangas/Komi-san-wa_-Comyushou-desu.jpg",
        "type": "Mangá",
        "year": "2016",
    },
    {
        "title": "Kuroshitsuji",
        "alternativeTitles": ["Black Butler"],
        "link": "../Kuroshitsuji/Obra.html",
        "image": "../../../../img/mangas/Kuroshitsuji.jpg",
        "type": "Mangá",
        "year": "2006",
    },
    {
        "title": "Lookism",
        "alternativeTitles": [""],
        "link": "../Lookism/Obra.html",
        "image": "../../../../img/mangas/Lookism.jpg",
        "type": "Manhwa",
        "year": "2014",
    },
    {
        "title": "Mahoutsukai no Yome",
        "alternativeTitles": [" The Ancient Magus' Bride"],
        "link": "../Mahoutsukai no Yome/Obra.html",
        "image": "../../../../img/mangas/Mahoutsukai-no-Yome.jpg",
        "type": "Mangá",
        "year": "2013",
    },
    {
        "title": "Marriage of Convenience",
        "alternativeTitles": ["Gyeolhon Jangsa"],
        "link": "../Marriage of Convenience/Obra.html",
        "image": "../../../../img/mangas/Marriage-of-Convenience.jpg",
        "type": "Manhwa",
        "year": "2022",
    },
    {
        "title": "Mashle: Magic and Muscles",
        "alternativeTitles": ["MASHLE"],
        "link": "../Mashle Magic and Muscles/Obra.html",
        "image": "../../../../img/mangas/Mashle-Magic-and-Muscles.jpg",
        "type": "Mangá",
        "year": "2020 - 2023",
    },
    {
        "title": "Mob Psycho 100",
        "alternativeTitles": [""],
        "link": "../Mob Psycho 100/Obra.html",
        "image": "../../../../img/mangas/Mob-Psycho-100.jpg",
        "type": "Mangá",
        "year": "2012 - 2017",
    },
    {
        "title": "Monster",
        "alternativeTitles": [""],
        "link": "../Monster/Obra.html",
        "image": "../../../../img/mangas/Monster.jpg",
        "type": "Mangá",
        "year": "1994 - 2001",
    },
    {
        "title": "My Husband Hides His Beauty",
        "alternativeTitles": ["Nampyeoni Mimoreul Sumgim"],
        "link": "../My Husband Hides His Beauty/Obra.html",
        "image": "../../../../img/mangas/My-Husband-Hides-His-Beauty.jpg",
        "type": "Manhwa",
        "year": "2020 - 2023",
    },
    {
        "title": "Nan Hao Shang Feng",
        "alternativeTitles": [""],
        "link": "../Nan Hao Shang Feng/Obra.html",
        "image": "../../../../img/mangas/Nan-Hao-Shang-Feng.jpg",
        "type": "Manhua",
        "year": "2019",
    },
    {
        "title": "Nana",
        "alternativeTitles": [""],
        "link": "../Nana/Obra.html",
        "image": "../../../../img/mangas/Nana.jpg",
        "type": "Mangá",
        "year": "2000 - 2009",
    },
    {
        "title": "Naruto",
        "alternativeTitles": [""],
        "link": "../Naruto/Obra.html",
        "image": "../../../../img/mangas/Naruto.jpg",
        "type": "Mangá",
        "year": "1999 - 2014",
    },
    {
        "title": "Noragami",
        "alternativeTitles": ["Noragami: Stray God"],
        "link": "../Noragami/Obra.html",
        "image": "../../../../img/mangas/Noragami.jpg",
        "type": "Mangá",
        "year": "2010 - 2024",
    },
    {
        "title": "Omniscient Reader",
        "alternativeTitles": ["Jeonjijeok Dokja Sijeom", "Omniscient Reader's Viewpoint"],
        "link": "../Omniscient Reader (novel)/Obra.html",
        "image": "../../../../img/mangas/Omniscient-Reader_novel_.jpg",
        "type": "Light Novel",
        "year": "2018",
    },
    {
        "title": "Omniscient Reader",
        "alternativeTitles": ["Jeonjijeok Dokja Sijeom", "Omniscient Reader's Viewpoint"],
        "link": "../Omniscient Reader/Obra.html",
        "image": "../../../../img/mangas/Omniscient-Reader.jpg",
        "type": "Manhwa",
        "year": "2020",
    },
    {
        "title": "One Piece",
        "alternativeTitles": [""],
        "link": "../One Piece/Obra.html",
        "image": "../../../../img/mangas/One-Piece.jpg",
        "type": "Mangá",
        "year": "1997",
    },
    {
        "title": "One Punch Man",
        "alternativeTitles": [""],
        "link": "../One Punch Man/Obra.html",
        "image": "../../../../img/mangas/One-Punch-Man.jpg",
        "type": "Mangá",
        "year": "2012",
    },
    {
        "title": "Operation Name Pure Love",
        "alternativeTitles": ["Jakjeonmyeong Sunjeong", "Operation: True Love"],
        "link": "../Operation Name Pure Love/Obra.html",
        "image": "../../../../img/mangas/Operation-Name-Pure-Love.jpg",
        "type": "Manhwa",
        "year": "2022",
    },
    {
        "title": "Oyasumi Punpun",
        "alternativeTitles": ["Goodnight Punpun"],
        "link": "../Oyasumi Punpun/Obra.html",
        "image": "../../../../img/mangas/Oyasumi-Punpun.jpg",
        "type": "Mangá",
        "year": "2007 - 2013",
    },
    {
        "title": "Parasyte",
        "alternativeTitles": ["Kiseijuu"],
        "link": "../obras/Parasyte/Obra.html",
        "image": "../../../../img/mangas/Parasyte.jpg",
        "type": "Mangá",
        "year": "1989 - 1995",
    },
    {
        "title": "Reality Quest",
        "alternativeTitles": ["Hyeonsil Quest"],
        "link": "../Reality Quest/Obra.html",
        "image": "../../../../img/mangas/Reality-Quest.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "Sakamoto Days",
        "alternativeTitles": [""],
        "link": "../Sakamoto Days/Obra.html",
        "image": "../../../../img/mangas/Sakamoto-Days.jpg",
        "type": "Mangá",
        "year": "2020",
    },
    {
        "title": "Second Life Ranker",
        "alternativeTitles": ["Du Beon Saneun Ranker"],
        "link": "../Second Life Ranker/Obra.html",
        "image": "../../../../img/mangas/Second-Life-Ranker.jpg",
        "type": "Manhwa",
        "year": "2019",
    },
    {
        "title": "Shingeki no Kyojin",
        "alternativeTitles": ["Attack on Titan"],
        "link": "../Shingeki no Kyojin/Obra.html",
        "image": "../../../../img/mangas/Shingeki-no-Kyojin.jpg",
        "type": "Mangá",
        "year": "2009 - 2021",
    },
    {
        "title": "Shotgun Boy",
        "alternativeTitles": [""],
        "link": "../Shotgun Boy/Obra.html",
        "image": "../../../../img/mangas/Shotgun-Boy.jpg",
        "type": "Manhwa",
        "year": "2021 - 2022",
    },
    {
        "title": "Solo Leveling: Ragnarok",
        "alternativeTitles": ["Na Honjaman Level-Up: Ragnarok", "Only I Level Up: Ragnarok"],
        "link": "../Solo Leveling Ragnarok/Obra.html",
        "image": "../../../../img/mangas/Solo-Leveling-Ragnarok.jpg",
        "type": "Manhwa",
        "year": "2024",
    },
    {
        "title": "Solo Leveling",
        "alternativeTitles": ["Na Honjaman Level-Up", "Only I Level Up"],
        "link": "../Solo Leveling/Obra.html",
        "image": "../../../../img/mangas/Solo-Leveling.jpg",
        "type": "Manhwa",
        "year": "2018 - 2023",
    },
    {
        "title": "Sono Bisque Doll wa Koi wo Suru",
        "alternativeTitles": [" My Dress-Up Darling"],
        "link": "../Sono Bisque Doll wa Koi wo Suru/Obra.html",
        "image": "../../../../img/mangas/Sono-Bisque-Doll-wa-Koi-wo-Suru.jpg",
        "type": "Mangá",
        "year": "2018",
    },
    {
        "title": "Sousou no Frieren",
        "alternativeTitles": ["Frieren: Beyond Journey's End"],
        "link": "../Sousou no Frieren/Obra.html",
        "image": "../../../../img/mangas/Sousou-no-Frieren.jpg",
        "type": "Mangá",
        "year": "2020",
    },
    {
        "title": "SPY × FAMILY",
        "alternativeTitles": [""],
        "link": "../SPY×FAMILY/Obra.html",
        "image": "../../../../img/mangas/SPY-x-FAMILY.jpg",
        "type": "Mangá",
        "year": "2019",
    },
    {
        "title": "SQ: Begin W/Your Name!",
        "alternativeTitles": ["SQ: Cong Ni De Ming Zi Kai Shi", "Tamen De Gushi", "Their Story"],
        "link": "../SQ Begin WYour Name!/Obra.html",
        "image": "../../../../img/mangas/SQ-Begin-WYour-Name.jpg",
        "type": "Manhua",
        "year": "2014",
    },
    {
        "title": "SSS-Class Revival Hunter",
        "alternativeTitles": ["SSS-geup Jasal Hunter"],
        "link": "../SSS-Class Revival Hunter/Obra.html",
        "image": "../../../../img/mangas/SSS-Class-Revival-Hunter.jpg",
        "type": "Manhwa",
        "year": "2020",
    },
    {
        "title": "Sun-Ken Rock",
        "alternativeTitles": [""],
        "link": "../Sun-Ken Rock/Obra.html",
        "image": "../../../../img/mangas/Sun-Ken-Rock.jpg",
        "type": "Mangá",
        "year": "2006 - 2016",
    },
    {
        "title": "Sweet Home",
        "alternativeTitles": [""],
        "link": "../Sweet Home/Obra.html",
        "image": "../../../../img/mangas/Sweet-Home.jpg",
        "type": "Manhwa",
        "year": "2017 - 2020",
    },
    {
        "title": "Sword Fanatic Wanders Through The Night",
        "alternativeTitles": ["A Dance of Swords in the Night", "Kare Chwihan Bameul Geotda"],
        "link": "../Sword Fanatic Wanders Through The Night/Obra.html",
        "image": "../../../../img/mangas/Sword-Fanatic-Wanders-Through-The-Night.jpg",
        "type": "Manhwa",
        "year": "2022",
    },
    {
        "title": "The Apothecary Diaries",
        "alternativeTitles": ["Kusuriya no Hitorigoto"],
        "link": "../The Apothecary Diaries/Obra.html",
        "image": "../../../../img/mangas/The-Apothecary-Diaries.jpg",
        "type": "Mangá",
        "year": "2017",
    },
    {
        "title": "The Beginning After the End",
        "alternativeTitles": [""],
        "link": "../The Beginning After the End/Obra.html",
        "image": "../../../../img/mangas/The-Beginning-After-the-End.jpg",
        "type": "Manhwa",
        "year": "2018",
    },
    {
        "title": "The Best Man In Charge",
        "alternativeTitles": ["Designated Bully", "Iljindamdangiljin"],
        "link": "../The Best Man In Charge/Obra.html",
        "image": "../../../../img/mangas/The-Best-Man-In-Charge.jpg",
        "type": "Manhwa",
        "year": "2022",
    },
    {
        "title": "The Boxer",
        "alternativeTitles": [""],
        "link": "../The Boxer/Obra.html",
        "image": "../../../../img/mangas/The-Boxer.jpg",
        "type": "Manhwa",
        "year": "2019",
    },
    {
        "title": "The Greatest Estate Designer",
        "alternativeTitles": ["Yeokdaegeum Yeongji Seolgyesa"],
        "link": "../The Greatest Estate Designer/Obra.html",
        "image": "../../../../img/mangas/The-Greatest-Estate-Designer.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "The Guy She Was Interested in Wasn't a Guy at All",
        "alternativeTitles": [" Ki ni Natteru Hito ga Otoko Janakatta"],
        "link": "../The Guy She Was Interested in Wasn_t a Guy at All/Obra.html",
        "image": "../../../../img/mangas/The-Guy-She-Was-Interested-in-Wasn_t-a-Guy-at-All.jpg",
        "type": "Mangá",
        "year": "2022",
    },
    {
        "title": "The Princess Imprints a Traitor",
        "alternativeTitles": ["Revolutionary Princess Eve", "Hwangnyeo", "Banyeokjareul Gaginsikida"],
        "link": "../The Princess Imprints a Traitor/Obra.html",
        "image": "../../../../img/mangas/The-Princess-Imprints-a-Traitor.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "The Promised Neverland",
        "alternativeTitles": ["Yakusoku no Neverland"],
        "link": "../The Promised Neverland/Obra.html",
        "image": "../../../../img/mangas/The-Promised-Neverland.jpg",
        "type": "Mangá",
        "year": "2016 - 2020",
    },
    {
        "title": "The Way to Protect the Female Lead’s Older Brother",
        "alternativeTitles": ["Roxana", "Yeojuingongui Oppareul Jikineun Bangbeop"],
        "link": "../The Way to Protect the Female Lead’s Older Brother/Obra.html",
        "image": "../../../../img/mangas/The-Way-to-Protect-the-Female-Lead_s-Older-Brother.jpg",
        "type": "Manhwa",
        "year": "2021",
    },
    {
        "title": "Tokyo Ghoul",
        "alternativeTitles": ["Tokyo Kushu"],
        "link": "../Tokyo Ghoul/Obra.html",
        "image": "../../../../img/mangas/Tokyo-Ghoul.jpg",
        "type": "Mangá",
        "year": "2011 - 2014",
    },
    //
    {
        "title": "Tokyo Revengers",
        "alternativeTitles": [""],
        "link": "../Tokyo Revengers/Obra.html",
        "image": "../../../../img/mangas/Tokyo-Revengers.jpg",
        "type": "Mangá",
        "year": "2017 - 2022",
    },
    {
        "title": "Tomie",
        "alternativeTitles": ["Ito Junji Kessakushuu: Tomie", "Ito Junji Kyoufu Manga Collection: Tomie"],
        "link": "../Tomie/Obra.html",
        "image": "../../../../img/mangas/Tomie.jpg",
        "type": "Mangá",
        "year": "1987 - 2000",
    },
    {
        "title": "Trash of the Count’s Family",
        "alternativeTitles": ["Lout of Count’s Family", "Baekjakgaui Mangnaniga Doeeotda"],
        "link": "../Trash of the Count’s Family/Obra.html",
        "image": "../../../../img/mangas/Trash-of-the-Count_s-Family.jpg",
        "type": "Manhwa",
        "year": "2020",
    },
    {
        "title": "Under the Oak Tree",
        "alternativeTitles": [" Sangsurinamu Arae"],
        "link": "../Under the Oak Tree/Obra.html",
        "image": "../../../../img/mangas/Under-the-Oak-Tree.jpg",
        "type": "Manhwa",
        "year": "2020",
    },
    {
        "title": "Unholy Blood",
        "alternativeTitles": ["White Blood"],
        "link": "../Unholy Blood/Obra.html",
        "image": "../../../../img/mangas/Unholy-Blood.jpg",
        "type": "Manhwa",
        "year": "2020 - 2022",
    },
    {
        "title": "Uzumaki: Spiral into Horror",
        "alternativeTitles": ["The Spiral", "Uzumaki"],
        "link": "../obras/Uzumaki/Obra.html",
        "image": "../../../../img/mangas/Uzumaki.jpg",
        "type": "Mangá",
        "year": "1998 - 1999",
    },
    {
        "title": "Vagabond",
        "alternativeTitles": [""],
        "link": "../Vagabond/Obra.html",
        "image": "../../../../img/mangas/Vagabond.jpg",
        "type": "Mangá",
        "year": "1998 - 2015",
    },
    {
        "title": "Veil",
        "alternativeTitles": [""],
        "link": "../Veil/Obra.html",
        "image": "../../../../img/mangas/Veil.jpg",
        "type": "Mangá",
        "year": "2019",
    },
    {
        "title": "Villains Are Destined to Die",
        "alternativeTitles": ["Agyeogui Ending-eun Jugeumppun", "The Villain’s Ending Is Death"],
        "link": "../Villains Are Destined to Die/Obra.html",
        "image": "../../../../img/mangas/Villains-Are-Destined-to-Die.jpg",
        "type": "Manhwa",
        "year": "2020",
    },
    {
        "title": "Vinland Saga",
        "alternativeTitles": [""],
        "link": "../obras/Vinland Saga/Obra.html",
        "image": "../../../../img/mangas/Vinland-Saga.jpg",
        "type": "Mangá",
        "year": "2005",
    },
    {
        "title": "Wind Breaker",
        "alternativeTitles": [""],
        "link": "../Wind Breaker/Obra.html",
        "image": "../../../../img/mangas/Wind-Breaker.jpg",
        "type": "Manhwa",
        "year": "2013",
    },
    {
        "title": "Yona of the Dawn",
        "alternativeTitles": ["Akatsuki no Yona"],
        "link": "../Yona of the Dawn/Obra.html",
        "image": "../../../../img/mangas/Yona-of-the-Dawn.jpg",
        "type": "Mangá",
        "year": "2009",
    },
];

function searchManga(query) {
    const searchTerm = query.toLowerCase();
    return mangas.filter(manga => {
        const titleMatch = manga.title.toLowerCase().includes(searchTerm);
        const altTitleMatch = manga.alternativeTitles.some(altTitle => altTitle.toLowerCase().includes(searchTerm));
        return titleMatch || altTitleMatch;
    });
}

function displaySearchResults(results) {
    const resultsContainer = document.getElementById('search-results');
    resultsContainer.innerHTML = '';

    if (results.length === 0) {
        resultsContainer.innerHTML = '<p style="font-weight: bold; color: #090A14; text-align: center; font-size: 18px;">Nenhum resultado encontrado.</p>';
        resultsContainer.classList.add('visible');
        return;
    }

    results.forEach(manga => {
        const resultItem = document.createElement('div');
        resultItem.classList.add('search-result-item');

        resultItem.innerHTML = `
        <a href="${manga.link}">
            <img class="result-image" src="${manga.image}" alt="${manga.title}">
        </a>
        <div class="result-details">
            <a href="${manga.link}">
                <h4>${manga.title}</h4>
            </a>
            <p>
                <svg width="25px" height="25px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M3.17157 2.17157C2 3.34315 2 5.22876 2 9V13C2 16.7712 2 18.6569 3.17157 19.8284C4.34315 21 6.22876 21 10 21H14C17.7712 21 19.6569 21 20.8284 19.8284C22 18.6569 22 16.7712 22 13V9C22 5.22876 22 3.34315 20.8284 2.17157C19.6569 1 17.7712 1 14 1H10C6.22876 1 4.34315 1 3.17157 2.17157ZM12.5074 15.7223L12.5 15.7262V7.28277L12.5219 7.27042C13.0752 6.95027 13.9685 6.47356 14.7 6.27079C15.2404 6.12099 15.9405 6.05197 16.5568 6.0217C17.3619 5.98216 18 6.64543 18 7.45154V12.9108C18 13.7437 17.3207 14.4151 16.4901 14.477C15.9839 14.5147 15.4375 14.5783 15 14.6852C14.1634 14.8896 13.1174 15.4009 12.5074 15.7223ZM6 7.49649V12.9108C6 13.7437 6.67934 14.4151 7.50991 14.477C8.01608 14.5147 8.56248 14.5783 9 14.6852C9.83655 14.8896 10.8826 15.4009 11.4926 15.7223L11.5 15.7262V7.31094C11.4881 7.30525 11.4763 7.29933 11.4646 7.29318C10.851 6.9711 9.8239 6.4721 9 6.27079C8.55592 6.16228 7.99967 6.09844 7.48717 6.06091C6.66539 6.00074 6 6.67251 6 7.49649Z" fill="#090A14"/>
                </svg> ${manga.type} - ${manga.year}
            </p>
        </div>
    `;

        resultsContainer.appendChild(resultItem);
    });
}

document.getElementById('search-bar').addEventListener('input', function() {
    const query = this.value.trim();
    const resultsContainer = document.getElementById('search-results');

    if (query.length === 0) {
        resultsContainer.innerHTML = '';
        resultsContainer.classList.remove('visible');
    } else {
        const searchResults = searchManga(query);
        displaySearchResults(searchResults);

        if (searchResults.length > 0) {
            resultsContainer.classList.add('visible');
        } else {
            resultsContainer.classList.add('visible');
        }
    }
});
